### ISSUE TITLE
[WIP] Webpack Contrib Label Set

### ISSUE THREAD

**Issue by d3viant0ne** [webpack-contrib/webpack-contrib-labels#3]
**Proposal By:** @d3viant0ne @bebraw 

**Scope:** All repositories in `webpack-contrib` 

## Motivation / Use Case

As a part of the standards effort and to simplify the effort to provide better visibility / cross-project maintenance tasks for the contrib team we are defining a standard set of labels to be used across the organization. A standard label set will also be a prerequisite of the `Contrib Bot` project.

It's also worth noting that without `priority` issues are just a meaningless blob of work. We need to make it easier for contributors, maintainers & admins to assess what requires effort and in what order.

Labels also need to have a consistent meaning. Severity & Priority need to be applied to issues by maintainers based on a common set of criteria or the effort loses it's effectiveness.

## Implementation

Labels are broken down into two parts (type & information) the first of which will be important to both the CLI tool and the Issue / PR BOT.

#### Breakdown
`<labelType>: <information>`
`labelType` === `severity || priority` ( always lower case )

### Issue Type
**Bug:**
&nbsp; &nbsp; Label Name: `type: Bug`
&nbsp; &nbsp; HEX Code: #d4c5f9

**Feature:**
&nbsp; &nbsp; Label Name: `type: Feature`
&nbsp; &nbsp; HEX Code: #d4c5f9

**Enhancement:**
&nbsp; &nbsp; Label Name: `type: Enhancement`
&nbsp; &nbsp; HEX Code: #d4c5f9

**Chore:**
&nbsp; &nbsp; Label Name: `type: Chore`
&nbsp; &nbsp; HEX Code: #d4c5f9

**RFC/Proposal:**
&nbsp; &nbsp; Label Name: `type: RFC/Proposal`
&nbsp; &nbsp; HEX Code: #d4c5f9

**Documentation:**
&nbsp; &nbsp; Label Name: `type: Documentation`
&nbsp; &nbsp; HEX Code: #d4c5f9

### Issue Severity ( Highest: 1 to Lowest: 5 )
**Severity 1:**
&nbsp; &nbsp; Label Name: `severity: 1 (security)`
&nbsp; &nbsp; HEX Code: #bfd4f2

**Severity 2:**
&nbsp; &nbsp; Label Name: `severity: 2 (regression)`
&nbsp; &nbsp; HEX Code: #bfd4f2

**Severity 3:**
&nbsp; &nbsp; Label Name: `severity: 3 (broken)`
&nbsp; &nbsp; HEX Code: #bfd4f2

**Severity 4:**
&nbsp; &nbsp; Label Name: `severity: 4 (inconvenient)`
&nbsp; &nbsp; HEX Code: #bfd4f2

**Severity 5:**
&nbsp; &nbsp; Label Name: `severity: 5 (confusing)`
&nbsp; &nbsp; HEX Code: #bfd4f2

### Issue Priority ( Highest: 1 to Lowest: 5 )
**Priority 1:**
&nbsp; &nbsp; Label Name: `priority: 1 (critical)`
&nbsp; &nbsp; HEX Code: #bfdadc

**Priority 2:**
&nbsp; &nbsp; Label Name: `priority: 2 (urgent)`
&nbsp; &nbsp; HEX Code: #bfdadc

**Priority 3:**
&nbsp; &nbsp; Label Name: `priority: 3 (required)`
&nbsp; &nbsp; HEX Code: #bfdadc

**Priority 4:**
&nbsp; &nbsp; Label Name: `priority: 4 (important)`
&nbsp; &nbsp; HEX Code: #bfdadc

**Priority 5:**
&nbsp; &nbsp; Label Name: `priority: 5 (nice to have)`
&nbsp; &nbsp; HEX Code: #bfdadc

### Issue Effort ( Easiest: 1 to Hardest: 4 ) 
**Effort 1:**
&nbsp; &nbsp; Label Name: `effort: 1 (my first commit)`
&nbsp; &nbsp; HEX Code: #fef2c0

**Effort 2:**
&nbsp; &nbsp; Label Name: `effort: 2 (easy hours)`
&nbsp; &nbsp; HEX Code: #fef2c0

**Effort 3:**
&nbsp; &nbsp; Label Name: `effort: 3 (medium days)`
&nbsp; &nbsp; HEX Code: #fef2c0

**Effort 4:**
&nbsp; &nbsp; Label Name: `effort: 4 (hard weeks)`
&nbsp; &nbsp; HEX Code: #fef2c0

### Issue Flags
**Has Pull Request:**
&nbsp; &nbsp; Label Name: `flag: Has pull request`
&nbsp; &nbsp; HEX Code: #c2e0c6

**Community:**
&nbsp; &nbsp; Label Name: `flag: Community help wanted`
&nbsp; &nbsp; HEX Code: #c2e0c6

**Needs More Info:**
&nbsp; &nbsp; Label Name: `flag: Needs more info`
&nbsp; &nbsp; HEX Code: #c2e0c6

### Pull Request
**Discuss:**
&nbsp; &nbsp; Label Name: `pr_action: Discuss`
&nbsp; &nbsp; HEX Code: #006b75

**Review:**
&nbsp; &nbsp; Label Name: `pr_action: Review`
&nbsp; &nbsp; HEX Code: #fbca04

**Rework:**
&nbsp; &nbsp; Label Name: `pr_action: Rework`
&nbsp; &nbsp; HEX Code: #d93f0b

**Blocked:**
&nbsp; &nbsp; Label Name: `pr_action: Blocked`
&nbsp; &nbsp; HEX Code: #b60205

**Merge:**
&nbsp; &nbsp; Label Name: `pr_action: Merge`
&nbsp; &nbsp; HEX Code: #0e8a16

### Status
**Pending:**
&nbsp; &nbsp; Label Name: `status: Pending`
&nbsp; &nbsp; HEX Code: #006b75

**Needs Triage:** Default label for any properly formatted issue not yet assigned a `type: & priority:`
&nbsp; &nbsp; Label Name: `status: Needs triage`
&nbsp; &nbsp; HEX Code: #1d76db

**Needs Reproduction:** Label for issue of `type: Bug` that requires an example repo or failing test case as a part of the triage process.
&nbsp; &nbsp; Label Name: `status: Needs repro`
&nbsp; &nbsp; HEX Code: `#fbca04`

**Declined:**
&nbsp; &nbsp; Label Name: `status: Declined`
&nbsp; &nbsp; HEX Code: #d93f0b

**Blocked**
&nbsp; &nbsp; Label Name: `status: Blocked`
&nbsp; &nbsp; HEX Code: #b60205

**Approved**
&nbsp; &nbsp; Label Name: `status: Approved`
&nbsp; &nbsp; HEX Code: #0e8a16

**Comment by bebraw** [comment]
A couple of notes:

* Would it make sense to merge enhancement and RFC/Proposal? Can proposals be about something else than about enhancements?
* Severity and issue scales are inverse. I would do priority 5 === highest. Then you can do priority 6 later if you need it.
* Effort - I would add "your first commit" kind of label for very easy ones for people that want to get into a project and need a starter task.
* Some kind of "needs more info" meta tag is needed.
* Status: declined probably contains "wontfix" so that's likely enough.

**Comment by d3viant0ne** [comment]
`RFC / Proposal` can also relate to a new feature or refactoring effort. 

`Enhancement` is an improvement in code to an existing feature 

I suppose I should put all the definitions in so some of these make more sense.

**Comment by d3viant0ne** [comment]
- [ ]`My First Commit` added to effort:
- [ ] `Need more info` added to status:
- [ ] `Severity` reordered

**Comment by sapegin** [comment]
What “flag: Good for community” means?

In my understanding ”Enhancement” is a proposal for enhancement until it’s accepted by maintainers.

**Comment by bebraw** [comment]
Maybe "Good for community" could be eliminated in favor of "Help wanted" without losing anything of value?

**Comment by d3viant0ne** [comment]
Merged the two
